spring:
  application:
    name: controle-financeiro
  datasource:
    url: jdbc:postgresql://localhost:5432/controle-financeiro
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: false
  config:
      activate:
        on-profile: test
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 7070

