spring:
  application:
    name: controle-financeiro
  datasource:
    url: jdbc:postgresql://localhost:5432/controle-financeiro
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  config:
    activate:
      on-profile: dev

server:
  port: 9090

