spring:
  application:
    name: controle-financeiro
  datasource:
    url: jdbc:postgresql://localhost:5432/controle-financeiro
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/master.xml

server:
  port: 9090
  servlet:
    context-path: /api

