spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/master.xml

server:
  port: 88000

