spring:
  application:
    name: controle-financeiro
  datasource:
    url: jdbc:postgresql://localhost:5432/controle_financeiro_db
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/master.xml

server:
  port: 8080
  servlet:
    context-path: "/api"
  error:
    include-stacktrace: never

