# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: gradle

on:
  pull_request:
    branches:
      - '*'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.2.1
        dependency-graph: generate-and-submit

    - name: Start PostgreSQL Container
      run: |
        docker run -d \
          --name postgres-container \
          -e POSTGRES_DB=controle-financeiro \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=postgres \
          -p 5432:5432 \
          postgres:latest

    - name: Wait for PostgreSQL to Start
      run: |
        docker exec postgres-container sh -c 'while ! pg_isready -h localhost -p 5432 -U postgres; do sleep 1; done'


    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew test

    - name: Stop and Remove PostgreSQL Container
      run: |
        docker stop postgres-container
        docker rm postgres-container

