name: gradle

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 23
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.2.1
          dependency-graph: generate-and-submit

      - name: Start PostgreSQL Container
        run: |
          docker run -d \
            --name postgres-container \
            -e POSTGRES_DB=controle_financeiro_db \
            -e POSTGRES_USER=postgres \
            -e POSTGRES_PASSWORD=postgres \
            -p 5432:5432 \
            postgres:latest

      - name: Wait for PostgreSQL to Start
        run: |
          docker exec postgres-container sh -c 'while ! pg_isready -h localhost -p 5432 -U postgres; do sleep 1; done'

      - name: Check with Gradle
        run: ./gradlew check

      - name: Stop and Remove PostgreSQL Container
        run: |
          docker stop postgres-container
          docker rm postgres-container

